# Multi-stage build for Task Management App
# Stage 1: Build frontend
FROM node:18-alpine AS frontend-builder

WORKDIR /app

# Copy frontend package files
COPY package*.json ./
COPY vite.config.ts ./
COPY tsconfig.json ./
COPY tsconfig.node.json ./

# Install frontend dependencies
RUN npm ci

# Copy frontend source
COPY src ./src
COPY index.html ./
COPY postcss.config.mjs ./

# Build frontend (API will be served from same origin, so use relative path)
ENV VITE_API_URL=/api
RUN npm run build

# Stage 2: Build backend
FROM node:18-alpine AS backend-builder

WORKDIR /app

# Copy backend package files
COPY server/package*.json ./

# Copy Prisma schema BEFORE npm ci (needed for postinstall script)
COPY server/prisma ./prisma

# Install backend dependencies (postinstall will run prisma generate)
RUN npm ci

# Copy backend source
COPY server/src ./src
COPY server/tsconfig.json ./

# Build (Prisma Client already generated by postinstall)
RUN npm run build

# Stage 3: Production
FROM node:18-alpine

WORKDIR /app

# Install dumb-init and OpenSSL for Prisma
RUN apk add --no-cache dumb-init openssl libc6-compat

# Copy backend package files
COPY server/package*.json ./

# Install production dependencies only
# Skip postinstall script (prisma generate) since Prisma CLI is not in production deps
# We copy the generated Prisma Client from builder stage instead
RUN npm ci --only=production --ignore-scripts

# Copy built backend from builder
COPY --from=backend-builder /app/dist ./dist
COPY --from=backend-builder /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=backend-builder /app/node_modules/@prisma ./node_modules/@prisma
COPY --from=backend-builder /app/prisma ./prisma

# Copy built frontend
COPY --from=frontend-builder /app/dist ./public

# Create directory for database (SQLite)
RUN mkdir -p /app/data

# Set environment variables (can be overridden in CapRover)
ENV NODE_ENV=production
ENV PORT=80
# DATABASE_URL must be set in CapRover environment variables (PostgreSQL format: postgresql://...)

# Expose port
EXPOSE 80

# Use dumb-init to handle signals properly
ENTRYPOINT ["dumb-init", "--"]

# Start the server (runs migrations first, then starts server)
CMD ["npm", "start"]

